In [1]:
import sqlite3
import pandas as pd
from sqlalchemy import create_engine

In [2]:
conn = sqlite3.connect("data.db")

df = pd.read_sql("select * from  userstable", con=conn)

conn.close()

In [3]:
df['Statut'] = 'utilisateur'
df['Statut'][8] = 'administrateur'
dummy_statut = pd.get_dummies(df['Statut']) # le code encode le statut du client.
df =  pd.merge(left=df,right=dummy_statut,left_index=True,right_index=True,)
df = df.drop(["Statut"], axis = 1)
df

           username  ... utilisateur
0             Jaslo  ...           1
1              toto  ...           1
2            Sino9Z  ...           1
3             moi34  ...           1
4              aze4  ...           1
5   Nom_utilisateur  ...           1
6              Ludo  ...           1
7             Molop  ...           1
8              AZER  ...           0
9               Cow  ...           1
10             Zipp  ...           1
11            Tatar  ...           1
12            Smaug  ...           1
13          Mumakil  ...           1
14           Ahsoka  ...           1
15            Elzée  ...           1
16           Margot  ...           1
17            Moana  ...           1
18            David  ...           1
19           Lucile  ...           1
20          Ludovic  ...           1
21         Delphine  ...           1
22             Héra  ...           1
23          Tauriel  ...           1
24            Laura  ...           1
25          Coralie  ...           1
26            Lydia  ...           1
27             Lisa  ...           1
28           Ruilin  ...           1
29             Marc  ...           1
30           Miguel  ...           1
31             Léna  ...           1
32           Samira  ...           1
33         Laurence  ...           1
34         Nohossat  ...           1
35          Antoine  ...           1
36    Marie-Margaux  ...           1
37          Barbara  ...           1
38           Marina  ...           1
39             Iris  ...           1
40          Pauline  ...           1
41          Kalimbo  ...           1
42             Delf  ...           1
43          Jasmine  ...           1
44          Aragorn  ...           1
45            Laury  ...           1
46        Cassandra  ...           1
47             Puma  ...           1
48             Arod  ...           1
49              Zou  ...           1
50              JB1  ...           1
51           Bintou  ...           1
52           Andrès  ...           1
53           Arnaud  ...           1
54           Gloria  ...           1

[55 rows x 4 columns]

In [4]:
df.to_csv('Users.csv',index = False) #pour sauvegarder la nouvelle database sous forme csv

In [5]:
pd.read_csv('Users.csv')

           username  ... utilisateur
0             Jaslo  ...           1
1              toto  ...           1
2            Sino9Z  ...           1
3             moi34  ...           1
4              aze4  ...           1
5   Nom_utilisateur  ...           1
6              Ludo  ...           1
7             Molop  ...           1
8              AZER  ...           0
9               Cow  ...           1
10             Zipp  ...           1
11            Tatar  ...           1
12            Smaug  ...           1
13          Mumakil  ...           1
14           Ahsoka  ...           1
15            Elzée  ...           1
16           Margot  ...           1
17            Moana  ...           1
18            David  ...           1
19           Lucile  ...           1
20          Ludovic  ...           1
21         Delphine  ...           1
22             Héra  ...           1
23          Tauriel  ...           1
24            Laura  ...           1
25          Coralie  ...           1
26            Lydia  ...           1
27             Lisa  ...           1
28           Ruilin  ...           1
29             Marc  ...           1
30           Miguel  ...           1
31             Léna  ...           1
32           Samira  ...           1
33         Laurence  ...           1
34         Nohossat  ...           1
35          Antoine  ...           1
36    Marie-Margaux  ...           1
37          Barbara  ...           1
38           Marina  ...           1
39             Iris  ...           1
40          Pauline  ...           1
41          Kalimbo  ...           1
42             Delf  ...           1
43          Jasmine  ...           1
44          Aragorn  ...           1
45            Laury  ...           1
46        Cassandra  ...           1
47             Puma  ...           1
48             Arod  ...           1
49              Zou  ...           1
50              JB1  ...           1
51           Bintou  ...           1
52           Andrès  ...           1
53           Arnaud  ...           1
54           Gloria  ...           1

[55 rows x 4 columns]

In [6]:
engine = create_engine('sqlite:////content/Users.db', echo=False)

df.to_sql('Users', con = engine, if_exists='replace' )

engine.execute("SELECT * FROM Users").fetchall()

[(0, 'Jaslo', '5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5', 0, 1),
 (1, 'toto', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 0, 1),
 (2, 'Sino9Z', 'dce88c29de615438681a0196eace3d34df3b1d37b17b7b1dade0801220589b59', 0, 1),
 (3, 'moi34', 'dd9f4e6d863f5f4e01b23ea5ba15ab177ca58dae82ae2f6979477805f3ee21a3', 0, 1),
 (4, 'aze4', '68f7a91ee05e239acab5df5dcf15dfca9970951347b1e42c8c108bfa48e5277d', 0, 1),
 (5, 'Nom_utilisateur', '487f2799e99aefa322824849f561e6e3b29c2ce51bc0d7f22ef38f2dd4f5099c', 0, 1),
 (6, 'Ludo', '9363f895169a58019e050825ee138dcd8e03df82a3d6575807427f002713eeb5', 0, 1),
 (7, 'Molop', '1d72b6d9326cf6738851ccc592ff93df00bb605609b7f6e525d7eeab513af494', 0, 1),
 (8, 'AZER', 'ae0dad1ce11a518bed1b4825ffeedec1e15a6197d170988b484c67cbb3351666', 1, 0),
 (9, 'Cow', '81d619410aed9df0a61db9e147066fb849edba9abeba7efe7f25940e0721757f', 0, 1),
 (10, 'Zipp', '779b93e516f272c0071fc1d69448697820db54329e27f32015573e47fa56ccfa', 0, 1),
 (11, 'Tatar', '3a5f994d7e356c5e0ecb45c1098fa8c34255ebecf0a3494b7acf5f4694c99046', 0, 1),
 (12, 'Smaug', '81785711e632ec828a41a024eafb51b4145628beb3d459d9444aed3d23169541', 0, 1),
 (13, 'Mumakil', 'cb1ddaf7abccebfba8f53aeebb1b167ebb3b0c6f99803bbb3b6309adab2dd89a', 0, 1),
 (14, 'Ahsoka', 'c7bd0733df865ceb41e4e5f7c5f824e58fe52742ee25ed39889ab4bbcb7bf39e', 0, 1),
 (15, 'Elzée', 'b20a7d254bdab4ee822c1973b2dca94197261860c5ad468b401c430a9d2c6ca4', 0, 1),
 (16, 'Margot', '54af2a2960e582263c45971cdd40da4ae31ede1db5395629d910f056479de12d', 0, 1),
 (17, 'Moana', '32670473e69d1e57fb36643a1319f96e4ba62819c077a05fb2f258223d6d41a3', 0, 1),
 (18, 'David', 'e9d7123aa42a83d1d222466c85cfe1bd76e16c82444ec572446bd1baec114dff', 0, 1),
 (19, 'Lucile', 'c0f0e8d1d30935353f892759a7b4260ea0d6ed321eb290c1b1f9e0d2070ea85f', 0, 1),
 (20, 'Ludovic', '518c0249c82f4736404121213d07a78b5dbf64f661caa34ef13d3f8faa705f90', 0, 1),
 (21, 'Delphine', '35b6764619deedd5c4b24ebc67994bac203efbd27c92ed32704f7055f7e65049', 0, 1),
 (22, 'Héra', 'abaa68c541efe0fc9bdc55fedf664487cf572ec27dbeb35223bdb4f8faa2e709', 0, 1),
 (23, 'Tauriel', '4e61bf4653c3f91f5c0ea3dc6497acb3bef3296ab60c9f97991fb2b75541587a', 0, 1),
 (24, 'Laura', '7fbd5b7382e7279bec8180c2836f699ba294f2a51564b4793cfb3ccbadaac594', 0, 1),
 (25, 'Coralie', '5a28fa1fccb69b988973e02d1f11e68f601eafb869d9487396c2c1210aa3da9a', 0, 1),
 (26, 'Lydia', '44353b1cdc490f7a285db1129074c67e63df5e319e8eb6bd99cb824688faa50f', 0, 1),
 (27, 'Lisa', '051ad22bcc8d81c21e6cbd30e602441242f38a2a281272aaa6f7b9a0ca04f7c2', 0, 1),
 (28, 'Ruilin', '7eee28584bedc65bd5b002f8b9654b2f407c28bcb758821430167eef4f6f0fee', 0, 1),
 (29, 'Marc', '3d16ade905831cc035a7e45a279935eb05755cfdfe70a6901e7e3bb87eb2acff', 0, 1),
 (30, 'Miguel', 'a3800bb76da92241f4a2784a73593b16ac722af895a2d978d1de304571cb1859', 0, 1),
 (31, 'Léna', 'b6f2920002873556366ad9f9a44711e4f34b596a892bd175427071e4064a89cc', 0, 1),
 (32, 'Samira', '9a319a0b2265a6ec34b06d59bcc8ce2cd543041ad9c1b595da27273ac42801b8', 0, 1),
 (33, 'Laurence', '8d4863a0a451970b9cbc79a1ee4cf0a8a9ada1fe3435d4cef4b1068890e3964b', 0, 1),
 (34, 'Nohossat', '8a4d8f4d84bf33c23e5bc784c60cb2482b305603b12c7d839bdfc5bf4272f597', 0, 1),
 (35, 'Antoine', 'c3a8c2d9b07aa7cd450c2b9b4a576f462a6e0e07e3286b6a8f9343017ee2976a', 0, 1),
 (36, 'Marie-Margaux', '0027d1ff23394f38225816da4172985496e864a05e2886f116644123d7abd16b', 0, 1),
 (37, 'Barbara', 'e7bfa387889d7cf6e9b08bf551cef2726d8c325a44ff9114aae2afc5631afc05', 0, 1),
 (38, 'Marina', '7506e51284b5864f508593a0613038004737be56635c9f7bd12939426365f85c', 0, 1),
 (39, 'Iris', 'a2693d6154f80a7fdca49563d208dd12b2f4ef63c8b3f0b5f76eb7a5e341ec4e', 0, 1),
 (40, 'Pauline', 'a58f63a55cec813f29650ef95d87a36b8f0a5f9e6a983739845e96abf3a06d0f', 0, 1),
 (41, 'Kalimbo', 'e4ca8001fef13e629d6da3c2e4d487a088ddf0ac1ae6c6c7d557a04093d9b9dc', 0, 1),
 (42, 'Delf', '62128be42907c0866965a87657982a8e0e6ee410aeab02af667a05696384ceb5', 0, 1),
 (43, 'Jasmine', '001dde0ccc7b7426a9d7606597dbb539187c8bdd9a774ca6fc6df37c25cb4b32', 0, 1),
 (44, 'Aragorn', 'a6ff6af6bc4a3572c2e6f740d4395e7a09985e18fd734070d41d03cf58bf92ef', 0, 1),
 (45, 'Laury', '127296f35f437087460bd2abfdf88096ac8eec2ed373a7b1238794881b1b0dbf', 0, 1),
 (46, 'Cassandra', 'abd8cfba151826bb7bf3de57387e9653e9d7f54d61e2e107213b3add4383cf91', 0, 1),
 (47, 'Puma', '58d183d9e9150abe3a51db530245cc17b106ca4cd012fc8806bc819599dc07f6', 0, 1),
 (48, 'Arod', '957bcfe9e994ff5de63cbe345d9f1e875a0a9e1df4ad21b3ae8aae6088c27a39', 0, 1),
 (49, 'Zou', 'a09bd0b800d1cc7c52fe72456fda6f8e3b8dc7f07809d3df5d2fcbcb69a6ad9f', 0, 1),
 (50, 'JB1', '1116e06b5952cf58d2a017510ca6065b99d17786cad54798ebdacebf18f0e41b', 0, 1),
 (51, 'Bintou', '897a48e4dbd050a44bd14dbcedd95318091cc11b4fb26ad26aa876ecc6e3baac', 0, 1),
 (52, 'Andrès', '72be275ef53e5485b368d0b019a7ac3025953198a5a4d9ba6b213dc4e6f30f2a', 0, 1),
 (53, 'Arnaud', 'ecafb12c9fda83ae35a365c653210d4e268490c16539883581df8478a7101ef1', 0, 1),
 (54, 'Gloria', '0432f342a614a780f9eab513e147bcb58153f746f1ddd9f67aa41e6fec2af1ce', 0, 1)]